<?php
/**
 * Desc:
 * Created by PhpStorm.
 * User: shantong
 * Date: 2018/9/10
 * Time: 18:26
 */

namespace backend\controllers;
use common\models\SystemLog;
use Yii;

class AdminLogController extends BaseController
{
	public function init()
	{
		if (Yii::$app->user->isGuest) {
			$url = Yii::$app->urlManager->createUrl('login/index');
			header("Location: $url");
			die;
		}
	}

	public function beforeAction($action)
	{
		parent::beforeAction($action); // TODO: Change the autogenerated stub
		// TODO 检查权限
		self::checkPermission();
		// 保存操作日志
		self::saveAdminLog();

		return true;
	}

	public static function checkPermission()
	{

	}

	/**
	 * @Desc: 保存操作日志
	 * @param array $data
	 * @return bool
	 */
	public static function saveAdminLog($data = [])
	{
		$request = Yii::$app->request;

		$moduleId = Yii::$app->controller->module->id;
		$route = strtolower(sprintf('%s/%s', Yii::$app->controller->id, Yii::$app->controller->action->id));
		$title = Yii::$app->params['actionTitle'][ $moduleId ][ $route ] ?? '';
		if (empty($title)) {
			return true;
		}
		$params = [
			'GET' => $request->get(),
			'POST' => $request->post(),
		];
		unset($params['GET']['_csrf_token_backend_xstnet']);
		// 密码不显示出来
		if (isset($params['POST']['password']) && !empty($params['POST']['password'])) {
			$params['POST']['password'] = '**********';
		}
		$data = array_merge([
			'user_id' => (int) Yii::$app->user->id,
			'nickname' => (string) Yii::$app->user->identity->nickname,
			'title' => $title,
			'route' => $route,
			'url' => $request->getUrl(),
			'params' => json_encode($params),
			'ip' => $request->getUserIP(),
			'request_method' => $_SERVER['REQUEST_METHOD'],
		], $data);

		$log = new SystemLog();
		$log->load($data, '');

		try {
			$log->saveModel();
		} catch (\Exception $e) {
			Yii::error('保存日志错误，错误原因'. $e->getMessage());
			Yii::error('日志数据: ');
			Yii::error($data);
		}
	}

}